### ISSUE TITLE
[META]: Interface

### ISSUE THREAD

**Issue by marcoasxd** [marcoasxd/Projeto-Interdisciplinar-II#6]
Caros colegas, tudo bem com vocês? O visual da tela de login está pronta, entretanto, faltam muitas coisas para que ela funcione. Irei deixar umas checkbox para quando o projeto for avançando, indo atualizando por aqui. Fiquem a vontade para editar aqui. 

(**IMPORTANTE**: Quem for mexer na tela de login, recomendo criar uma branch separada e ir fazendo implementações ou mudanças lá para não atrapalhar a principal.)

- [x] Versão inicial do design
- [x] Prototipação
- [x] Identidade visual
- [x] Cores principais do sistema (com ajuda do @Leopoldo154)
- [x] Responsividade
- [ ] JavaScript
- [x] Back-end com conexão com o banco de dados (@Leopoldo154, @ppaFonso, @jvavcastro)

Como enviei no grupo, a projeção inicial da tela de login para versão desktop seria essa:

![image](https://user-images.githubusercontent.com/102104507/161383208-bd0f3f45-4a05-440e-90a4-901f8bca00ea.png)

**Comment by marcoasxd** [comment]
update (4 mai, 2022): Queria aproveitar esse issue para colocar todas as telas. Todas estão "prontas", portanto, falta implementar o backend. Deixarei esse issue aberto para possíveis implementações.

**Comment by marcoasxd** [comment]
Projeto foi encerrado, estou fechando esse issue.
